# Site settings
title: 
  en : 2016 RMLL Security Track
  fr : Thème Sécurité RMLL 2016
email: contact.sec2016@rmll.info
description: 
  en : The RMLL Security Track will be an autonomous event in 2016. Come to share Free Software and Security passion with others unicorns :)
  fr : Le thème Sécurité des RMLL sera un événement autonome en 2016. Venez partager votre passion pour le code libre et la Sécurité avec les autres licornes :)
index:
  en : 
  fr : accueil.html
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
permalink: /:title/

#traductions
translate:
  en:
    home:
      name: "About"
      url: "/"
    program:
      name: "Program"
      url: "/program/"
    archives:
      name: "Archives"
      url: "/#archives"
    practical:
      name: "Practical informations & contact"
      url: "/#contact"
    sponsors:
      name: "Sponsors"
      url: "/#sponsors"
  fr:
    home:
      name: "Accueil"
      url: "/accueil.html"
    program:
      name: "Programme"
      url: "/programme/"
    archives:
      name: "Archives"
      url: "/accueil.html#archives"
    practical:
      name: "Informations pratiques & contact"
      url: "/accueil.html#contact"
    sponsors:
      name: "Partenaires"
      url: "/accueil.html#sponsors"

twitter_username:
github_username:

# Build settings
markdown: kramdown
